name: SocialMediaIE
channels:
  - defaults
  - conda-forge
  - pytorch
  #- intel
dependencies:
  - python=3.6
  - numpy==1.15.4
  - scipy==1.2.1
  - pandas
  - scikit-learn==0.20.2
  - tqdm
  - ipython
  - ipykernel
  - pytorch==1.0.0
  #- cudatoolkit=9.0
  #- mkl
  #- intel-openmp
  - umap-learn
  - pip
  - pip:
    - allennlp==0.8.3
